<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="fr">
<head>

<TITLE><? echo $title; ?>  </TITLE>


<META NAME="Keywords" CONTENT="externalisation, prestataire, inventaire, donneur d'ordres, entreprise extérieure,  contractant, contracté,  contrat, maintenance, entretien, interactif, audit, audit maintenance, diagnostic, ingenieur, ingénieur, conseil, maint, industrie, industriel, auditeur, maintenabilité, maintenabilite, fiabilité, fiabilite, disponibilité, disponibilite, normes, contrat, ratios, indicateurs, durabilité, durabilite, controles, contrôles, thermographie, arret, informatique, expertise, amdec,
preventif, defaillance, curatif, consulting, previsionnel, plan de maintenance, TRS, TPM">


<META NAME="Description" CONTENT="<? echo $description; ?>  ">


<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<META NAME="ROBOTS" CONTENT="all">
<meta name="classification" content="externalisation, prestataire, inventaire, donneur d'ordres, entreprise extérieure,  contractant, contracté,  contrat, maintenance, entretien, interactif, audit, audit maintenance, diagnostic, ingenieur, ingénieur, conseil, maint, industrie, industriel, auditeur, maintenabilité, maintenabilite, fiabilité, fiabilite, disponibilité, disponibilite, normes, contrat, ratios, indicateurs, durabilité, durabilite, controles, contrôles, thermographie, arret, informatique, expertise, amdec,
preventif, defaillance, curatif, consulting, previsionnel, plan de maintenance, TRS, TPM">
<META NAME="Author" CONTENT="Laloux Guillaume, consultant maintenance">
<META NAME="Generator" CONTENT="Laloux Ingexpert maintenance">
<META NAME="Creation_Date" CONTENT="3/12/2002">
<META NAME="revisit-after" CONTENT="7 days">
<meta name="language" content="fr">




  <!-- début partie modifiée-->
<link href="style_page.css" rel="stylesheet" type="text/css">
  <!-- fin partie modifiée-->

</head>

<body>
<form name="ecriture" method="post" action="https://dev.ingexpert.com/ingexpert/lettre_adhesion_maintenance.php">
  <div id="conteneur">
    <!--debut include-->
    <div id="haut">
      <!--debut logo-->
            <div id="logo">
            <img src="images/logo-ingexpert-conseil.jpg" border="0" width="238" height="30" alt="Maintenance enligne Industrielle Tertiaire Transport Biomédicale" >
            </div>
        <!--fin logo-->

            <div class="bao" style="position: absolute; top: 0em; left: 51em;  " >

            <br><a href="https://dev.ingexpert.com/ingexpert/maintenance-contact-telephone-ingexpert.php" class="bao">Contact</a>
            | <a href="https://dev.ingexpert.com/conseil-maintenance" class="bao">Forum</a>
            | <font color="red">Newsletter </font><input name="mail" value="Saisissez votre email ici" type="text" size="22"  onFocus="this.value='';"><input type="submit" value="OK" name="envoyer" value="Envoyer" class="inputOK"></a>
            | <a href="https://dev.ingexpert.com/maintenance-recherche.php" class="bao">Rechercher</a>
            </div>
  <div class="titree" style="position: absolute; top: 2em; left: 0em; font-family: Arial ; font-size:14px; bold; color: #8F8F8F;">Les sites d'Ingexpert: </div>




 <!--debut boutons sites ingexpert-->

<div style="position: absolute; top: 5em; left: 0em; ">

<p>
<a href="https://www.ingexpert.fr" class="boutoningexpert">INGEXPERT_________La société Ingexpert</a>
</p>

<div style="float:left; margin:14px 0px 4px 0px; ">
<p>
<a href="https://dev.ingexpert.com/maintexpert" class="boutonmaintexpert">MAINTEXPERT__Cours sur la maintenance</a>
</p>

<div style="float:left; margin:14px 0px 4px 0px; ">
<p>
<a href="https://enligne.ingexpert.fr" class="boutonoutil">EnLigne_____Outils maintenance en ligne</a>
</p>

<div style="float:left; margin:14px 0px 4px 0px; ">

 </div>
</div>
</div>
</div>


 <!--fin boutons sites ingexpert-->

    <!--Début titre -->
 <div class="titree" style="position: absolute; top: 3em; left: 16em; font-family: Arial ; font-size:20px; bold; color: #8E8E8E;">Conseil, assistance, formation pour le management de la maintenance </div>
 <div class="titree" style="position: absolute; top: 7em; left: 40em; font-family: Arial ; font-size:14px; bold; color: #8E8E8E;">Cours sur la maintenance</div>
 <!--Fin titre -->




  <!--debut menu-->
 <div class="m">
<div class="m4" style="position: absolute; top: 12em; left: 26em; ">

				<ul class="m4">
                    <li><a href="php_theorie_maintenance__definitions.php"><span>THEORIE DE LA MAINTENANCE</span></a></li>
					  <li><a href="php_divers_maintenance__formation.php"><span>DIVERS</span></a></li>


				</ul>
			</div>
        	</div>
<!-- Fin menu -->


      </div>

    <!--fin include-->
    <div id="contenu">
         <div class="dte" style="position: absolute; top: 15em; left: 0em; ">
              <!--Titre--><br><div align="right" style="font-family: Arial ; font-size:16px; bold; color: #5D6B95;"><span class="titre"><? echo $menu; ?>
              <!-- Bonhommes -->  <img src="images/persos_basmenupage.gif"><br>
              <!--Livre a telecharger--><div align="left"><a href="https://dev.ingexpert.com/images/Faire-evoluer-votre-maintenance.pdf">  <img src="images/vignette_telechargdoc.gif" border="0"></div><br></a>
              <!--Personne position Lotus--><img src="images/bas_page.gif">
         </div>
         <div class="dte" style="position: absolute; top: 16em; left: 28em; ">
           <span class="filariane">Vous êtes ici : <? echo $vouseteici; ?> </span><br><br><br>


<map name="ingexpert">
<area shape="rect" coords="68,18,174,40" href="https://dev.ingexpert.com/enligne/" alt="Nos Experts en ligne">
<area shape="rect" coords="4,19,65,39" href="https://dev.ingexpert.com" alt="Ingexpert"><area shape="rect" coords="68,18,174,40" href="#" alt="Nos Experts en ligne">


</form>
</map>


